version: "3.8"
services:
  db:
    image: postgres:13.10
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_DB: chatrooms
      POSTGRES_USER: chatrooms
      POSTGRES_PASSWORD: chatrooms
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  rabbitmq:
    image: 'rabbitmq:management'
    ports:
      - "56720:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: chatrooms
      RABBITMQ_DEFAULT_PASS: chatrooms
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 

volumes:
  local_pgdata:
  rabbitmq_data:
