version: "3.8"
services:
  db:
    image: postgres:13.10
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_DB: chatrooms
      POSTGRES_USER: chatrooms
      POSTGRES_PASSWORD: chatrooms
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata:
